### ISSUE TITLE
webpack support for media files

### ISSUE THREAD

**Issue by EranGrin** [daycademy/vue-csr-to-ssr#1]
Hello, 
Very clean example,
I'm trying to use your nice example with img assets, but I receive an img src of [object Object]
I would be glad to know the reason, or maybe you can even add an example 

Many Thanks

**Comment by FlorianWoelki** [comment]
Hey there :)

the reason for that is the current version of `url-loader`. You can just parse `esModule: false` in the `options` object in the `webpack.common.js` file.
